package com.a203.smartcart.model.constant;

public enum ErrorCode {

    EMPTY_FILE_EXCEPTION, IO_EXCEPTION_ON_IMAGE_UPLOAD, NO_FILE_EXTENTION,
    INVALID_FILE_EXTENTION, PUT_OBJECT_EXCEPTION, IO_EXCEPTION_ON_IMAGE_DELETE


}
